# Generated by Django 4.0.4 on 2023-02-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(default=0, max_length=1000000),
            preserve_default=False,
        ),
    ]
